- hosts: all
  become: true
  tasks:
  - name: update repository index
    apt:
      update_cache: yes
    when: ansible_distribution in ["Ubuntu","Debian"] 
    
  - name: install nginx package
    apt:
      name: nginx
      state: latest
    when: ansible_distribution =="Ubuntu"
  

  - name: update repository index
    dnf:
      update_cache: yes
    when: ansible_distribution =="CentOS"
    
  - name: install nginx package
    dnf:
      name: nginx
      state: latest
    when: ansible_distribution =="CentOS"
        
